Updated executive summary
Green-Software-Foundation/software_carbon_intensity pull request #121
Opened 2021-10-18 21:17 UTC by jawache

See: https://github.com/Green-Software-Foundation/software_carbon_intensity/issues/116

2021-10-19 08:39 UTC, aecurrie commented
I like it. Excellent improvement in clarity, especially for individuals coming to the spec cold (i.e. without having read the closed issues)

2021-10-19 15:09 UTC, buchananwp commented
This is a great improvement to the executive summary, but I do believe we should do a few extra things to resolve #116 (i've updated that issue to reflect this)

1. bump the 'core characteristics' section to the top for readability
2. Incorporate comments from 'getting started' with core characteristics
3. include high-level equation summary

I can try and work on this branch before the next GSF call if needed

2021-10-19 15:40 UTC, jawache commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +Reducing an SCI score is only possible through changes to a software system to use less physical hardware, less energy, or consume lower-carbon energy sources. Neutralisations such as carbon offsets
Good point will add.

2021-10-19 20:39 UTC, buchananwp approved these changes
will break feedback into separate PRs for simplicity

2021-10-21 11:17 UTC, atg-abhishek requested changes
@jawache thank you for putting this together. Some changes needed but otherwise looking great!

2021-10-21 11:17 UTC, atg-abhishek commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +The SCI encourages calculation using granular real-world data, which is challenging to obtain in some of these environments, particularly the public cloud. The Green Software Foundation is committed
@jawache including "hosting suppliers" pushes us back into a more cloud-centric approach. Perhaps some other phrasing that can help us avoid that?

2021-10-21 11:17 UTC, atg-abhishek commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +- **What**: Decide on the software boundary, what components of a software system to include.
```suggestion
- **What**: Decide on the software boundary, i.e. the components of a software system to include.
```

2021-10-21 11:17 UTC, atg-abhishek commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +- **Scale**: The SCI is a rate, carbon emissions per one unit of a baseline called R. The next step is to pick the baseline which best describes how the application scales.
```suggestion
- **Scale**: The SCI is a rate, carbon emissions per one unit of a baseline called `R`. The next step is to pick the baseline which best describes how the application scales. 
```

2021-10-21 11:17 UTC, atg-abhishek commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +- **Measure**: Calculate a rate, an SCI, for every software component. The SCI of the whole application is the average of the SCIs for every software component in the system.
```suggestion
- **Measure**: Calculate a rate, an SCI value, for every software component. The SCI value of the whole application is the average of the SCI values for every software component in the system.
```

2021-10-21 11:17 UTC, atg-abhishek commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +What you cannot measure, you cannot improve.
```suggestion
> "If you can't measure it, you can't improve it." - Peter Drucker
```

2021-10-21 11:17 UTC, atg-abhishek commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +What you cannot measure, you cannot improve.
Correcting the quote and adding in the attribution, especially since this is the opening line of the SCI

2021-10-21 12:33 UTC, jawache commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +The SCI encourages calculation using granular real-world data, which is challenging to obtain in some of these environments, particularly the public cloud. The Green Software Foundation is committed
@aecurrie was the one that suggested this approach, what you thing @aecurrie if we just used suppliers? There is also a rather large problem that most hardware suppliers do not provide data regarding their embodied emissions?

2021-10-21 12:36 UTC, jawache commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> -#### Applications Of This Specification
Oh do you mean "private data center" -> "any on-premise application"

2021-10-21 12:55 UTC, jawache commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> -#### Applications Of This Specification
Done!

2021-10-21 15:03 UTC, jawache commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +Reducing an SCI score is only possible through changes to a software system to use less physical hardware, less energy, or consume lower-carbon energy sources. Neutralisations such as carbon offsets
Done

2021-10-26 15:34 UTC, merged