Boundary Inclusion Requirement
Green-Software-Foundation/software_carbon_intensity pull request #70
Opened 2021-09-02 22:28 UTC by Henry-WattTime

Established the boundary requirement. Based on discussion in issue #56

2021-09-02 22:48 UTC, Henry-WattTime commented
Should 'software boundary' be a term in the dictionary?

2021-09-07 14:56 UTC, vaughanknight commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +The calculation of software carbon intensity must include include all supporting infrastructure and systems that significantly contributes to the software operation. Supporting infrastructure and sys
doubled up on a word "must include include"

2021-09-08 15:50 UTC, vaughanknight commented
It's looking good.  I won't be able to make the weeklly call so putting it in a comment here

2021-09-09 11:37 UTC, atg-abhishek commented
@Henry-WattTime the term you requested has been added [here](https://github.com/Green-Software-Foundation/Dictionary/issues/25) as an issue.

2021-09-09 11:38 UTC, atg-abhishek requested changes
@Henry-WattTime it looks good but we need minor changes: the words must and may should be capitalized so that we indicate that they carry a very specific connotation as specified in the dictionary and the references for the SCI spec itself.

2021-09-09 11:45 UTC, atg-abhishek commented
oh and @Henry-WattTime actually it might be a good idea to bullet the list of items included to make them more evident rather than having them as a part of a single sentence.

2021-09-09 15:23 UTC, dtoakley commented
Agree with both capitalizing the MUST and MAY, as well as listing the items in a bullet list. Other than that, this looks good!

2021-09-09 15:37 UTC, merged

2021-09-09 15:37 UTC, Henry-WattTime commented
Approved by working group 2020/09/09