Adding building, training, redundancy and failover to the boundary list
Green-Software-Foundation/software_carbon_intensity pull request #79
Opened 2021-09-13 04:57 UTC by vaughanknight

Adding building, training, redundancy and failover to the boundary list, details in Issue #78 

3 bullet points added - Building, Training, Redundancy and failover
Formatting - the paragraph following the boundary list is now separated so it doesn't append to the last bullet point.

2021-09-15 07:20 UTC, atg-abhishek requested changes
@vaughanknight looks good, I've made a minor suggestion that I think clarifies redundancy and failover better.

2021-09-15 07:20 UTC, atg-abhishek commented on Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md
> +- redundancy and failover
```suggestion
- resources to support redundancy
- resources to support failover
```

2021-09-15 09:03 UTC, vaughanknight reviewed
Wording updates for clarity done in line with your reocmmendations @atg-abhishek

2021-09-15 10:24 UTC, atg-abhishek approved these changes
LGTM!

2021-09-16 16:21 UTC, atg-abhishek commented
Approved by WG during meeting

2021-09-16 16:22 UTC, merged